/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.blooddonationandlabs;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vbbvi
 */
public class BillScreen extends javax.swing.JFrame {
SingletonClass singleton=SingletonClass.getInstance();

 ArrayList<TestModel> testList = new ArrayList<>();
 

    /**
     * Creates new form BillScreen
     */
    public BillScreen() {
        initComponents();
        getTestName();
       
//        getTest();
    }
      public void getTestName() {
    try{
        Statement stmt = null;
        String selectStatement = "SELECT * FROM labTest";
        PreparedStatement ps = singleton.connection.prepareCall(selectStatement);
        ResultSet rs = ps.executeQuery();
        String [] headerName = {"Sr No.","Test Name","Price"};
        DefaultTableModel model = new DefaultTableModel(null, headerName);
        testNameTable.setModel(model);
        
        Object[] row = new Object[3];
        while(rs.next()){
              row[0] = rs.getInt("id");
              row[1] = rs.getString("Name");
              row[2]=rs.getString("Price");
             
              model.addRow(row);
        }
    }catch(SQLException sqlexception){
    System.out.println("exception 1"+sqlexception.getMessage());
    }
   }
//     public void  getTestList(int id,String name,String price){
//           Statement stmt = null;
//        ResultSet resultSet = null;
//        String[] headerNames = {"Sr.no", "Name", "Price"};
//        DefaultTableModel model = new DefaultTableModel(null, headerNames);
//        billTable.setModel(model);
//         model.setRowCount(0);
//        Object[] row = new Object[5];
//        try {
//            stmt = singleton.connection.createStatement();
////            resultSet = stmt.executeQuery("SELECT * FROM labTest");
////            while (resultSet.next()) {
//                testList.add(new TestModel(resultSet.getInt(id), resultSet.getString(name), resultSet.getString(price)));
////            }
//            for (TestModel item : testList) {
//                System.out.println(item);
//                row[0] = item.getId();
//                row[1] = item.getName();
//                row[2] = item.getPrice();
//               
//                model.addRow(row);
//                System.out.println("Length"+testList.listIterator());
//            }
//        } catch (SQLException ex) {
//            System.out.println("Print");
////            Logger.getLogger(testList.class.getName()).log(Level.SEVERE, null, ex);
//        }
//      }
//    public void  getTest(){
//        try{
//        Statement stmt = null;
//        String selectStatement = "SELECT * FROM labTest";
//        PreparedStatement ps = singleton.connection.prepareCall(selectStatement);
//        ResultSet rs = ps.executeQuery();
//        String [] headerName = {"Sr No.","Test Name","Test Description","Test Price"};
//        DefaultTableModel model = new DefaultTableModel(null, headerName);
//        billTable.setModel(model);
//        
//        Object[] row = new Object[4];
//        while(rs.next()){
//              row[0] = rs.getInt("id");
//              row[1] = rs.getString("Name");
//              row[2]=rs.getString("Description");
//              row[3]=rs.getString("Price");
//             
//              model.addRow(row);
//        }
//    }catch(SQLException sqlexception){
//    System.out.println("exception 1"+sqlexception.getMessage());
//    }  
//      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        testNameTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        Bill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        testNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testNameTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testNameTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(testNameTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Test Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Customer Name");

        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(billTable);

        Bill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bill.setText("Bill");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bill)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bill)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testNameTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testNameTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)testNameTable.getModel();
        int selectedrow = testNameTable.getSelectedRow();
        String id = dtm.getValueAt(selectedrow,0).toString();
        int rowID=Integer.parseInt(id);
        String name=dtm.getValueAt(selectedrow,1).toString();
        String price=dtm.getValueAt(selectedrow,2).toString(); 
        testList.add(new TestModel(rowID, name, price));
        String [] headerName = {"ID","Name", "Price"};
        DefaultTableModel dtmBill = new DefaultTableModel(null,headerName);
        Object[] row = new Object[3];
                for(TestModel billModel : testList){
                    System.out.println("billModel"+billModel);
                    row[0]=billModel.getId();
                    row[1]=billModel.getName();
                    row[2]=billModel.getPrice();
                    dtmBill.addRow(row);
                    
                }
        billTable.setModel(dtmBill);
        
//        testList.add(0,(id));
//        testList.add(1,(name));
//        testList.add(2,(price));
        System.out.println("idod");
        System.out.println("id"+id);
        System.out.println("name"+name);
        System.out.println("price"+price);
    }//GEN-LAST:event_testNameTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bill;
    private javax.swing.JTable billTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable testNameTable;
    // End of variables declaration//GEN-END:variables

   
}
